# Generated by Django 5.0.6 on 2024-06-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWeb', '0003_rename_contrasena_usuario_password_remove_usuario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id_comic', models.AutoField(db_column='idComic', primary_key=True, serialize=False)),
                ('editorial', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=70)),
                ('precio', models.IntegerField()),
                ('autor', models.CharField(max_length=200)),
                ('idioma', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('formato', models.CharField(max_length=50)),
                ('disponible', models.IntegerField()),
                ('edi_original', models.TextField()),
            ],
        ),
    ]
