# Generated by Django 5.0 on 2024-06-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWeb', '0004_comic'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='isbn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='ruta_img',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
