# Generated by Django 5.0 on 2024-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWeb', '0005_comic_isbn_comic_ruta_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='ruta_img',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
