# Generated by Django 5.0 on 2024-06-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWeb', '0006_alter_comic_ruta_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='ruta_img',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
