# Generated by Django 5.0.6 on 2024-06-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWeb', '0007_alter_comic_ruta_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='isbn',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
